---
title: "Reproducible Research: Peer Assessment 1"
author: "Miseon Song"
date: "Tuesday, December 13, 2014"
output: html_document
---


This is Peer Assessment 

## Loading and preprocessing the data

```{r}
setwd("C:/Users/msong/Documents/msong/Coursera/Reproducing_Research/data/")
getwd()
dat=read.csv("activity.csv",header=T)
# use as.Date( ) to convert strings to dates 
dat$date <- as.Date(dat$date)

dat1=na.omit(dat)
```

## What is mean total number of steps taken per day?

```{r}
steps.sum=tapply(dat1$steps,dat1$date,sum)
hist(steps.sum, main='Total # of steps per day (w/o missing)')
c(avg=mean(steps.sum),med=median(steps.sum))
```

## What is the average daily activity pattern?
```{r}
y1=tapply(dat1$steps,dat1$interval,mean)
length(y1)
x=names(y1)
plot(x,y1,type='l', main='Time series plot of 5-min intervals')
which.max(y1)
```

## Imputing missing values

```{r}
# 3 : Compute no. of missing values
dim(dat)[1] - dim(dat1)[1]

#
# imputing missing values (using mean for 5-minute interval)
#
ndays=length(table(dat$date)); ndays
cnt=length(table(dat$interval))

y2=rep(y1,times=ndays)

dat2=dat
dat2$steps=ifelse(is.na(dat2$steps),y2,dat2$steps)
```


## Are there differences in activity patterns between weekdays and weekends?

```{r}
#### compute 
steps.sum.imp=tapply(dat2$steps,dat2$date,sum)
hist(steps.sum.imp,main='Total # of steps per day (using imp data)')
c(avg=mean(steps.sum.imp),med=median(steps.sum.imp))

#### Weekdays and weekends

dat3=dat2
dat3$date=as.Date(dat3$date)

dat3$wktype=ifelse(weekdays(dat3$date) %in% c('토요일','일요일'),'weekend','weekday')
#head(dat3)
#tail(dat3)
table(dat3$wktype)

# Panel Plot
y3 <- tapply(dat3$steps, list(dat3$interval,dat3$wktype), mean)

y4=data.frame(Interval=as.integer(row.names(y3)),y3)

y5=reshape(y4, varying=c("weekday","weekend"),
               v.names="steps", timevar="wktype",
               times=c("weekday","weekend"),
               new.row.names=1:576, 
             direction = "long")
library(lattice)
xyplot(steps ~Interval| wktype, data=y5, layout=c(1,2), type='l',
                 ylab='Number of Steps')

```


